use_frameworks!

target 'StravaSwift_Example' do
  pod 'StravaSwift', :path => '../'

  target 'StravaSwift_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  end
end
